permalink: /:categories/:title/
url: "http://example.com"
full_name: "Developer Theme "
first_name: "About"
last_name: "Me"
blog_title: "Title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2025"
google_analytics_code: ""
aboutme: "I like ramen noodles with cream."
